name: KnokkoCore
main: nl.knokko.core.plugin.CorePlugin
version: 1.12 10
commands:
  knokkocore:
    description: Test command for the Knokko Core Plugin... only use when I ask you to
    useage: /knokkocore itemattribute/itemname/test
    aliases: [knokko]