name: KnokkoCore
main: nl.knokko.core.plugin.CorePlugin
version: 1.12 8
commands:
  knokkocore:
    description: Test command for the Knokko Core Plugin... dont use this
    useage: /knokkocore itemattribute/itemname/test
    aliases: [knokko]